version: '3.8'

services:
  postgres:
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:?error}
      POSTGRES_DB: nexus_dev
    volumes:
      - pgdata_dev:/var/lib/postgresql/data

  redis:
    ports:
      - '6379:6379'

  server:
    ports:
      - '9900:9900'
    environment:
      NODE_ENV: development
      NEXUS_LOG_LEVEL: debug
      DATABASE_URL: postgresql://postgres:${POSTGRES_PASSWORD:?error}@postgres:5432/nexus_dev
    volumes:
      - ./server/src:/app/src:ro
      - ./server/tests:/app/tests:ro

  frontend:
    ports:
      - '5173:80'

volumes:
  pgdata_dev:
