/**
 * file-watcher.ts — Workspace File Synchronizer.
 *
 * Watches local workspace files and syncs coding conventions from memory
 * into IDE configuration files (.cursorrules, CLAUDE.md, etc.).
 * This is a file watcher only - does NOT perform actual remote sync.
 */

import { db } from '../db/client.js';
import { memories } from '../db/client.js';
import { appendAudit } from '../lib/audit.js';
import { readFile, writeFile, mkdir } from 'node:fs/promises';
import { resolve, dirname } from 'node:path';
import { desc, sql } from 'drizzle-orm';

export interface SyncResult {
  filesWritten: string[];
  conventionsInjected: number;
  backupsCreated: string[];
}

/**
 * Extract coding conventions from high-importance memories and format
 * them as IDE-compatible markdown.
 */
async function extractConventions(): Promise<string> {
  const top = await db.query.memories.findMany({
    where: sql`${memories.importance} >= 0.6 AND ${memories.kind} IN ('preference', 'fact', 'reflexion')`,
    orderBy: [desc(memories.importance)],
    limit: 20,
  });

  if (!top.length) return '# No coding conventions found in memory yet.';

  const lines: string[] = [
    '# NEXUS Project Context (Auto-Synced)',
    '',
    '> This file is automatically generated from NEXUS 2.0 memory.',
    '> Do not edit manually — run `nexus sync-workspace` to update.',
    '',
  ];

  for (const m of top) {
    lines.push(`## ${m.title}`);
    lines.push(m.content);

    let tagsArray: string[] = [];
    if (m.tags) {
      if (Array.isArray(m.tags)) {
        tagsArray = m.tags;
      } else if (typeof m.tags === 'string') {
        try {
          const parsed = JSON.parse(m.tags);
          if (Array.isArray(parsed)) {
            tagsArray = parsed;
          }
        } catch {
          // ignore parsing error
        }
      }
    }
    if (tagsArray.length) {
      lines.push(`\\n*Tags: ${tagsArray.map((t) => `#${t}`).join(' ')}*`);
    }
    lines.push('');
  }

  return lines.join('\\n');
}

/**
 * Sync memory conventions into workspace IDE files.
 * Backs up existing files before overwriting.
 */
export async function syncWorkspace(workspaceDir: string, actor: string): Promise<SyncResult> {
  const conventions = await extractConventions();
  const filesWritten: string[] = [];
  const backupsCreated: string[] = [];

  const targets = [
    { path: '.cursorrules', content: conventions },
    { path: 'CLAUDE.md', content: conventions },
    {
      path: 'AGENTS.md',
      content:
        conventions +
        '\\n\\n## How To Use NEXUS\\nUse nexus_recall before tasks; nexus_remember for durable facts; nexus_capture at session end.',
    },
  ];

  for (const target of targets) {
    const fullPath = resolve(workspaceDir, target.path);
    try {
      // Backup existing file if it exists
      try {
        const existing = await readFile(fullPath, 'utf8');
        if (existing.trim()) {
          const backupPath = `${fullPath}.bak`;
          await writeFile(backupPath, existing, 'utf8');
          backupsCreated.push(backupPath);
        }
      } catch (readErr) {
        // Only tolerate ENOENT (file doesn't exist). Re-throw permission errors.
        if (
          readErr instanceof Error &&
          'code' in readErr &&
          (readErr as NodeJS.ErrnoException).code !== 'ENOENT'
        ) {
          throw readErr;
        }
      }

      // Write new content
      await mkdir(dirname(fullPath), { recursive: true });
      await writeFile(fullPath, target.content, 'utf8');
      filesWritten.push(target.path);
    } catch {
      // Skip files we can't write (permissions, etc.)
    }
  }

  const conventionCount = conventions.split('\\n## ').length - 1;

  await appendAudit(
    'workspace.synced',
    {
      filesWritten,
      backupsCreated,
      conventionsInjected: conventionCount,
    },
    actor
  );

  return { filesWritten, conventionsInjected: conventionCount, backupsCreated };
}
