/**
 * services/workspace-sync.ts — Workspace Code Injection.
 *
 * Automatically extracts coding conventions from memory and injects them
 * into local IDE configuration files (.cursorrules, CLAUDE.md, etc.)
 * so agents always have up-to-date project context.
 */
import { db } from "../db/client";
import { memories } from "../db/client.js";
import { appendAudit } from "../lib/audit.js";
import { writeFileSync, readFileSync, mkdirSync } from "node:fs";
import { resolve, dirname } from "node:path";
import { desc, sql } from "drizzle-orm";

export interface SyncResult {
  filesWritten: string[];
  conventionsInjected: number;
  backupsCreated: string[];
}


/**
 * Extract coding conventions from high-importance memories and format
 * them as IDE-compatible markdown.
 */
async function extractConventions(): Promise<string> {
  const top = await db.query.memories.findMany({
    where: sql`${memories.importance} >= 0.6 AND ${memories.kind} IN ('preference', 'fact', 'reflexion')`,
    orderBy: [desc(memories.importance)],
    limit: 20,
  });

  if (!top.length) return "# No coding conventions found in memory yet.";

  const lines: string[] = [
    "# NEXUS Project Context (Auto-Synced)",
    "",
    "> This file is automatically generated from NEXUS 2.0 memory.",
    "> Do not edit manually — run `nexus sync-workspace` to update.",
    "",
  ];

  for (const m of top) {
    lines.push(`## ${m.title}`);
    lines.push(m.content);
    if (m.tags.length) lines.push(`\n*Tags: ${m.tags.map((t) => `#${t}`).join(" ")}*`);
    lines.push("");
  }

  return lines.join("\n");
}

/**
 * Sync memory conventions into workspace IDE files.
 * Backs up existing files before overwriting.
 */
export async function syncWorkspace(workspaceDir: string, actor: string): Promise<SyncResult> {
  const conventions = await extractConventions();
  const filesWritten: string[] = [];
  const backupsCreated: string[] = [];

  const targets = [
    { path: ".cursorrules", content: conventions },
    { path: "CLAUDE.md", content: conventions },
    { path: "AGENTS.md", content: conventions + "\n\n## How To Use NEXUS\nUse nexus_recall before tasks; nexus_remember for durable facts; nexus_capture at session end." },
  ];

  for (const target of targets) {
    const fullPath = resolve(workspaceDir, target.path);
      try {
        // Backup existing file if it exists
        try {
          const existing = readFileSync(fullPath, "utf8");
          if (existing.trim()) {
            const backupPath = `${fullPath}.bak`;
            writeFileSync(backupPath, existing, "utf8");
            backupsCreated.push(backupPath);
          }
        } catch (readErr) {
          // Only tolerate ENOENT (file doesn't exist). Re-throw permission errors.
          if (readErr instanceof Error && "code" in readErr && (readErr as NodeJS.ErrnoException).code !== "ENOENT") {
            throw readErr;
          }
        }

      // Write new content
      mkdirSync(dirname(fullPath), { recursive: true });
      writeFileSync(fullPath, target.content, "utf8");
      filesWritten.push(target.path);
    } catch {
      // Skip files we can't write (permissions, etc.)
    }
  }

  const conventionCount = conventions.split("\n## ").length - 1;

  await appendAudit("workspace.synced", {
    filesWritten, backupsCreated, conventionsInjected: conventionCount,
  }, actor);

  return { filesWritten, conventionsInjected: conventionCount, backupsCreated };
}
